project:
  type: website
  output-dir: docs
  resources:
    - data/**
    - alignments/**
    - scripts/**
    - downloads/**

website:
  title: "Masterclass AI Genomica Ovarica"

format:
  html:
    theme: cosmo
